[project]
name = "site-backup"
version = "1.0.0"
description = "A tool to create backups of WordPress and HumHub instances"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto",
    "coloredlogs",
    "python-dateutil",
    "humanfriendly",
    "PyMySQL",
    "phply",
    "dsnparse",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-logging",
    "mock",
    "pylint",
    "flake8",
    "flake8-pep3101",
    "flake8-string-format",
]

[project.scripts]
sitebackup = "sitebackup:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["backup"]

[tool.uv]
dev-dependencies = [
    "pytest",
    "pytest-logging",
    "mock",
    "pylint",
    "flake8",
    "flake8-pep3101",
    "flake8-string-format",
    "black>=25.1.0",
]
