[project]
name = "site-backup"
version = "1.0.0"
description = "A tool to create backups of WordPress and HumHub instances"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto",
    "coloredlogs",
    "python-dateutil",
    "humanfriendly",
    "PyMySQL",
    "phply",
    "dsnparse",
]

[project.scripts]
sitebackup = "sitebackup:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["backup"]

[tool.uv]
dev-dependencies = [
    "pytest",
    "pytest-logging",
    "mock",
    "pylint",
    "flake8",
    "flake8-pep3101",
    "flake8-string-format",
    "black>=25.1.0",
    "requests",
]

[tool.pytest.ini_options]
markers = [
    "integration: marks tests as integration tests (may require external services)",
    "unit: marks tests as unit tests",
    "slow: marks tests as slow-running tests",
]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"
# By default, skip integration and slow tests
# Use: uv run pytest -m integration  to run integration tests
# Use: uv run pytest -m "not integration and not slow"  to run only fast unit tests
